### ISSUE TITLE
Handle email alerts for sensor service

### ISSUE THREAD

**Issue by abhishek-kumar-piyush** [TransparentPath/buildly-core#103]
**Description**
When a sensor is not assigned to a shipment but its GPS location is changing, sensor service raises an alert saying "SensorID is moving but has not been assigned to a Shipment".
Now in the email, we have option to redirect user back to the shipment, where we identify shipment by shipment_id,
but in this case we won't have a shipment_id (since sensor is not assigned to a particular shipment). Which will raise error.

Related ticket: [#167](https://github.com/TransparentPath/sensor_service/issues/167)

**Comment by yasmin2496** [comment]
Duplicate issue - https://github.com/TransparentPath/buildly-core/issues/104
