### ISSUE TITLE
Configuration of datamesh

### ISSUE THREAD

**Issue by vishalajackus** [TransparentPath/buildly-core#69]
- [x] Configuration via script using endpoint
- [x] Test and find any missing and required changes
- [x]  Test timing required for datamesh endpoint vs normal endpoint
- [x]  Join record function for one to one mapping by exporting model
- [x] Test Shipment <-> Items join entries
- [x] create endpoint for UUID in services
- [x] Test Shipment <-> Gateway join entries
- [x] core <-> shipment integration 
- [x] Update detail view in shipment model to test datamesh
- [x] Change code in client.py of core to accept uuid
- [x] Write join function for Custody model with shipment uuid
- [x] Write join function for Shipment model with item 
- [x] write join function for shipment model with gateway UUID
- [x] write join function for gateway model with custodian UUID
- [x] write join function for gateway model with organization
- [x] write join function for shipment model with organization
- [x] write join function for custody model with custodian
- [x] data mesh async configuration
- [x] consortium permission issue
- [x]  create datamesh documentation

**Comment by mthombare** [comment]
we are keeping on hold due to the architectural changes

**Comment by yasmin2496** [comment]
On hold for now as there are some changes around the whole architecture
